server:
  port: 8087

spring:
  application:
    name: sharding-jdbc-demo
  profiles:
    active: dev
  datasource:
    url: jdbc:shardingsphere:classpath:sharding.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver

